server:
  port: 8888
spring:
  sql:
    init:
      schema-locations: classpath:/sql/init.sql
      mode: never
  datasource:
    dynamic:
      primary: db_XMall_user
      strict: false
      datasource:
        db_XMall_user:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/db_XMall_user?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&collation=utf8_bin
          username: root
          password: 1544
          hikari:
            minimum-idle: 5
            maximum-pool-size: 10
        db_XMall_goods:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/db_XMall_goods?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&collation=utf8_bin
          username: root
          password: 1544
          hikari:
            minimum-idle: 5
            maximum-pool-size: 10
        db_XMall_store:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/db_XMall_store?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&collation=utf8_bin
          username: root
          password: 1544
          hikari:
            minimum-idle: 5
            maximum-pool-size: 10
        db_XMall_order:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/db_XMall_order?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&collation=utf8_bin
          username: root
          password: 1544
          hikari:
            minimum-idle: 5
            maximum-pool-size: 10
        db_XMall_communication:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/db_XMall_communication?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&collation=utf8_bin
          username: root
          password: 1544
          hikari:
            minimum-idle: 5
            maximum-pool-size: 10
        db_XMall_after_sale:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/db_XMall_after_sale?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&collation=utf8_bin
          username: root
          password: 1544
          hikari:
            minimum-idle: 5
            maximum-pool-size: 10
        db_XMall_preference:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/db_XMall_preference?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&collation=utf8_bin
          username: root
          password: 1544
          hikari:
            minimum-idle: 5
            maximum-pool-size: 10

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
